### ISSUE TITLE
Set `separateMultipleMinor` for `python` to `"true"` in Renovate configs

### ISSUE THREAD

**Issue by 34j** [browniebroke/pypackage-template#663]
**Is your feature request related to a problem? Please describe.**
I am frustrated that Renovate PRs for Python version updates are never automatically merged because it is very rare to be able to update to the latest minor version of Python at once (e.g. when relying on libraries such as numpy and numba).

**Describe the solution you'd like**
Change the settings **after** this issue (feature request) is resolved.
https://github.com/renovatebot/renovate/issues/6576
https://github.com/renovatebot/renovate/pull/24538

**Additional context**
- It might be better to configure each repository individually.
- Related: #597
- Sorry for opening so many issues.

**Comment by browniebroke** [comment]
That sounds sensible, yes. Would you mind sending the PR to my base configs? https://github.com/browniebroke/renovate-configs/blob/main/cpython.json
