### ISSUE TITLE
Support https://reuse.software/

### ISSUE THREAD

**Issue by ypid** [browniebroke/pypackage-template#733]
**Is your feature request related to a problem? Please describe.**
I would like to have solid licensing of my software.

**Describe the solution you'd like**
https://reuse.software/ is the best approach to do that I know of.

**Additional context**
I have been using REUSE for some time now. Adding the license info to every file looks bulky at first but as each file might be under a different license, I came to like this explicit way of doing things.

**Comment by browniebroke** [comment]
Thanks but no, I'm not interested.

**Comment by ypid** [comment]
Works for me. Your template is still the best I found ;-)
